library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(scales)
library(lubridate)
library(readr)

setwd("D:/GitHub/CA-Private-Colleges")

# This CSV was generated by hand coding the forms in the 2nd PRA production
enrollments <- read_csv("data/cleaned/enrollments.csv")

# --- Pivot multiple enrollment date columns into long format ---
enr <- enrollments %>%
  pivot_longer(
    cols      = starts_with("Enrollment Date"),
    names_to  = "date_number",
    values_to = "Enrollment_Date"
  ) %>%
  filter(!is.na(Enrollment_Date)) %>%
  mutate(
    Enrollment_Date = mdy(Enrollment_Date),
    date_number = str_extract(date_number, "\\d+")
  )

# verify
cat("Date range:", as.character(range(enr$Enrollment_Date, na.rm = TRUE)), "\n")
cat("NAs:", sum(is.na(enr$Enrollment_Date)), "\n")
cat("Rows:", nrow(enr), "\n")

# --- Identify school column ---
char_cols <- names(enrollments)[sapply(enrollments, is.character)]
school_col <- if ("School" %in% names(enrollments)) {
  "School"
} else if ("AGENCY_NAME" %in% names(enrollments)) {
  "AGENCY_NAME"
} else {
  setdiff(char_cols, names(enrollments)[grepl("Enrollment", names(enrollments))])[1]
}

# --- Order schools by first enrollment date ---
enr <- enr %>%
  rename(School = !!school_col) %>%
  group_by(School) %>%
  mutate(first_date = min(Enrollment_Date, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(School = reorder(School, first_date))

# --- Axis setup ---
xrng <- range(enr$Enrollment_Date, na.rm = TRUE)
x0   <- floor_date(xrng[1], "year")
x1   <- ceiling_date(xrng[2], "year")
year_breaks <- seq(x0, x1, by = "1 year")

# --- Caption: 2013 enrollment span ---
d2013   <- filter(enr, year(Enrollment_Date) == 2013)
start13 <- min(d2013$Enrollment_Date, na.rm = TRUE)
end13   <- max(d2013$Enrollment_Date, na.rm = TRUE)
days13  <- as.integer(end13 - start13) + 1L
cap <- sprintf(
  "All 2013 enrollments occurred between %s and %s (%d days)\nSource: Controller PRA Production Parts 1 & 2",
  format(start13, "%b %d"), format(end13, "%b %d"), days13
)

# --- Plot ---
ggplot(enr, aes(x = Enrollment_Date, y = School)) +
  geom_point(size = 1.6, alpha = 0.8) +
  scale_x_date(
    limits       = c(x0, x1),
    breaks       = year_breaks,
    labels       = label_date("%Y"),
    minor_breaks = NULL,
    expand       = expansion(mult = c(0.01, 0.01))
  ) +
  labs(
    title   = "Private School Enrollment in Intercept Program by Date",
    x       = "",
    y       = "",
    caption = cap
  ) +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.3),
    axis.text.x        = element_text(angle = 0, hjust = 0.5, vjust = 0.5)
  )


ggsave(
  filename = "figures/Figure1.png",
  width    = 10,
  height   = 6,
  dpi      = 300,
  bg       = "white"
)